### ISSUE TITLE
Approval Files formatter should include arguments' name

### ISSUE THREAD

**Issue by aneveux** [WriteThemFirst/approvals-java#1]
When computing tests for methods with several arguments, *approval files* should be formatted so all the arguments' names are kept in the file.

Given a method `foo(a,b,c)` which is tested by our framework, and producing `result` when called,
When *approval tests* are computed and the *approval files* are generated,
Then the produced file should be formatted as follows:

```
a=x; b=y; c=z; output=result;
```

So the file remains readable by a human.

**Comment by tyrcho** [comment]
@aneveux I have no idea if this is feasible ...
