### ISSUE TITLE
Allow to compare full directories instead of only files

### ISSUE THREAD

**Issue by aneveux** [WriteThemFirst/approvals-java#11]
When computing *approval tests*, the framework should allow not only to compare single files, but to compare full directories containing several files/folders.

Given a batch method, generating directories and files,
When running the approval tests,
Then the framework should compare all the generated data (files and folders hierarchy) with a reference one, committed along with the source code.

**Comment by tyrcho** [comment]
compare folder.received with folder.approved instead of comparing in the resources each file.approved with file.received => DONE in e0db55298c055814b1c7de6c303226d3b4f5f73d

**Comment by tyrcho** [comment]
[demo code in this class](../blob/master/src/test/java/org/demo/simple/ApproveFolder.java)

**Comment by tyrcho** [comment]
@aneveux @jmdesprez Would you please test this feature from your side also ? Then we can release it in 0.4 :D
