### ISSUE TITLE
Allow the developer to customize the merge tool to be used from an environment variable

### ISSUE THREAD

**Issue by aneveux** [WriteThemFirst/approvals-java#4]
When executing a merge tool for reviewing *approval* files, the framework should first search for a `DIFFTOOL` environment variable. If it is set, the tool specified by this variable should be executed by default.

Note:

- [x] Documentation has to be written for that feature

**Comment by tyrcho** [comment]
something similar was implemented in [0.9.0](https://github.com/WriteThemFirst/approvals-java/releases/tag/v0.9.0)
